apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hsds
  name: hsds
  namespace: hsds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsds
  template:
    metadata:
      labels:
        app: hsds
    spec:
      containers:
        - name: head
          image: hdfgroup/hsds:sha-3e9c651
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1G"
              cpu: "50m"
            limits:
              memory: "1G"
              cpu: "100m"
          volumeMounts:
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 5100
          env:
            - name: NODE_TYPE
              value: head_node
            - name: HEAD_PORT
              value: 5100 
            - name: TARGET_SN_COUNT
              value: 1
            - name: TARGET_DN_COUNT
              value: 1
        - name: sn
          image: hdfgroup/hsds:sha-3e9c651
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1G"
              cpu: "50m"
            limits:
              memory: "1G"
              cpu: "100m"
          volumeMounts:
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 5101
          env:
            - name: NODE_TYPE
              value: sn
            - name: HEAD_PORT
              value: 5100 
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: arctic-minio-secrets
                  key: MINIO_ROOT_USER
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: arctic-minio-secrets
                  key: MINIO_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /info
              port: 5101
            initialDelaySeconds: 5
            periodSeconds: 60
        - name: dn
          image: hdfgroup/hsds:sha-3e9c651
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/sbin/killall5", "-15"]
          resources:
            requests:
              memory: "2G"
              cpu: "50m"
            limits:
              memory: "2G"
              cpu: "100m"
          volumeMounts:
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 6101
          env:
            - name: NODE_TYPE
              value: dn
            - name: HEAD_PORT
              value: 5100 
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: arctic-minio-secrets
                  key: MINIO_ROOT_USER
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: arctic-minio-secrets
                  key: MINIO_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /info
              port: 6101
            initialDelaySeconds: 5
            periodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: hsds-config
        - name: override
          configMap:
            name: hsds-override
