apiVersion: v1
kind: ConfigMap
metadata:
  name: hsds-override
  namespace: hsds
data:
  override.yml: >+
    log_level: DEBUG
    
    bucket_name: arctic-hsds
    
    server_name: Highly Scalable Data Service (HSDS) on RC Kubernetes for UVA Arctic (test)
    
    password_salt: 4ff6c98c3824474b964e361055926a6e
    
    hsds_endpoint: http://hsds.pods.uvarc.io
    
    aws_s3_gateway: http://arctic-minio-service.hsds.svc.cluster.local:8080

binaryData: {}
