apiVersion: v1
kind: ConfigMap
metadata:
  name: hsds-override
  namespace: hsds
data:
  override.yml: >+
    log_level: DEBUG
    
    bucket_name: arctic-hsds
    
    server_name: Highly Scalable Data Service (HSDS) on RC Kubernetes for UVA Arctic 
    
    password_salt: 
    
    hsds_endpoint: http://hsds.pods.uvarc.io
    
    aws_s3_gateway: http://arctic-minio-service.hsds.svc.cluster.local:9000

    chunk_mem_cache_expire: 0

    chunk_mam_cache_size: 1000000000

    metadataa_mem_cache_expire: 0
    
    metadata_mem_cache_size: 256m

    max_task_count: 400

binaryData: {}
