apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hobo
  name: hobo
  namespace: hsds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hobo
  template:
    metadata:
      labels:
        app: hobo
    spec:
      containers:
        -
          name: hobo-request
          # Use this image for AWS deployment
          #image: "530483214727.dkr.ecr.us-west-2.amazonaws.com/hobo:v11"
          # Use this image for microk8s deployment
          image: "hdfgroup/hobo-request:v12"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1G"
              cpu: "50m"
            limits:
              memory: "1G"
              cpu: "100m"
          volumeMounts:
          - name: conf
            mountPath: "/conf/"
          env:
          - name: "HSDS_USERNAME"
            valueFrom:
              secretKeyRef:
                name: arctic-hobo-secrets
                key: HSDS_USERNAME
          - name: "HSDS_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: arctic-hobo-secrets
                key: HSDS_PASSWORD
          - name: "HOBO_CLIENT_ID"
            valueFrom:
              secretKeyRef:
                name: arctic-hobo-secrets
                key: HOBO_CLIENT_ID
          - name: "HOBO_CLIENT_SECRET"
            valueFrom:
              secretKeyRef:
                name: arctic-hobo-secrets
                key: HOBO_CLIENT_SECRET
      volumes:
      - name: conf
        configMap:
          name: hobo-conf
            
