apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arctic-hobo-secrets
  namespace: hsds
spec:
  encryptedData:
    hobo-secrets.txt: AgCvHZm8nMXf+GVIhtm5KoySL/UEBp9sUCsjBUpruCed1imwzvbnHuqmIUi9/q/rhBKW7EEcjPZxpIe5lJxdSTvklbsiUjKcA+bvYs56eVO9ZWlXWy/FzADlhSnN9Qx3INozzhCt3vrIFgquua4p7dzNCM1j/AXErkz1t3cDwMDEsDN47TrrMJ2o7qDW+E9CXRlsY/qucAXXfV9ydeVqZrLHdJUQjNtLy6Fef6tS0A89Kg0lp4rhtDp0sY6LBy/i9mQIcW19MQxYkH6+knwibJzqJ1w8JCxohJSsMhgp/UZrOg7p3JtDI5rErgwROg8TBscTWyuHBu6NtF2HPQztEV/ZaKUXAprkRx6WO65pPxriWczMPhLizfHlcDOQG5ZPgCwHvZHq4+4Axd0pplZbQjWMAveDP+UbdMAzfC504ydUx0Mi6KXevkHKkVkwV0WYyw87fD+JZ5hMECahhTukGS1rCmUFseVmnjRBICfYcwfrmoXuZDVCSshnhAoee+2Ce4KD2rI7V+OJUONJxIxgSv3zPK3vPDZqMSb3cPyzcOFaRwyLqpfZqCDVx5jOW3OYa06KjTldoHzJhvmvZKE8XjrHW1pL724zRIBT6EoVmGhc/xfIzWJqLnE+/KTiP50djbxv0llBmqmBvRx/XoVLBqPPclyIUafubAga8oG9PVlaxBYQ8Xe9pNffqB+x4hZTFmiLoGG9UX17UEp7VHyB4H0fGPeDUJC9UFPguffFoEaXpPUqpEWwnoxdTXIDdC6uaVsWkzyIXlUmjrqI7X7k7r5Th4d1jCRdlaBuTVQ/AD3lVkUuQ0SCNbDF8+NgTAC0CfOIsF0N+1YXMw3b4rNN+UEKSv9Vvw9SSEaw9glqdn8Z3L9pRAJfX5qrq15UJX8puBMQ1zEimVA=
  template:
    metadata:
      creationTimestamp: null
      name: arctic-hobo-secrets
      namespace: hsds

