apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arctic-minio-nfs-pvc
  namespace: hsds
spec:
  #storageClassName: arctic-minio-sc
  accessModes:
    - ReadWriteMany  #must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
