apiVersion: v1
kind: Service
metadata:
  name: arctic-minio-service
  namespace: hsds
spec:
  selector:
    app: arctic-minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: web
      protocol: TCP
      port: 9001
      targetPort: 9001
